import Head from "next/head";
import Image from "next/image";
import NavBar from "../components/navBar.tsx";
import SearchBarHome from "../components/searchBarhome.tsx";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | JSA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        style={{
          backgroundImage: `url("/guyinsuit.jpg")`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          height: "100vh",
        }}
      >
        <NavBar />
        <Box
          style={{
            display: "flex",
            height: "80vh",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <SearchBarHome />
        </Box>
      </Box>
    </>
  );
}
