import Head from "next/head";
import Image from "next/image";

import NavBar from "../components/navBar.tsx";
import SearchBar from "../components/searchBar.tsx";
import { Box } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        style={{
          // backgroundImage: `url("/homebg.jpg")`,
          backgroundSize: "cover",
          height: "100vh",
        }}
      >
        <NavBar />
        <Box
          style={{
            display: "flex",
            height: "80vh",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <SearchBar />
        </Box>
      </Box>
    </>
  );
}
